# Generated by Django 4.2.10 on 2024-03-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('seen', 'Seen'), ('approved', 'Approved')], default='new', max_length=20),
        ),
    ]
